
saveplot        = './'
cases          = ['baseline', 'hill', 'little_hill', 'realistic_extreme']
paths           = cases
tttitle         = cases
tttitles        = tttitle
shorttt         = tttitle


;saveplot        = './'
;cases          = ['MERIDIANI_tau050', 'MERIDIANI_tau100', 'MERIDIANI_tau200', 'MERIDIANI_tau500']
;paths           = cases
;tttitle         = ['tau = 0.5' $
;                  ,'tau = 1.0' $
;                  ,'tau = 2.0' $
;                  ,'tau = 5.0' $
;                  ]
;tttitles        = tttitle
;shorttt         = tttitle
