saveplot        = './'
cases           = ['../MERIDIANI_tau100' $
                  , '../MERIDIANI_tau100_wind10' $
                  , '../MERIDIANI_tau100_wind20' $
;                  , '../MERIDIANI_tau500' $
;                  , '../MERIDIANI_tau500_wind20' $
                  , '../MERIDIANI_tau050' $
                  , '../MERIDIANI_tau100_extreme' $
                  ]
paths           = cases
tttitle         = ['tau = 1' $
                  ,'tau = 1, wind = 10 m s!U-1!N' $
                  ,'tau = 1, wind = 20 m s!U-1!N' $
;                  ,'tau = 5, wind = 0 m s!U-1!N' $
;                  ,'tau = 5, wind = 20 m s!U-1!N' $
                  ,'tau = 0.5' $
                  ,'tau = 1, extreme soil' $
                  ]
tttitles        = tttitle
shorttt         = tttitle
