;;;;;*************************************** PLOT TITLES
	subtitle_user	=	''
	subtitle_user	=	'' ;'LT = 03:00am  /  Ls = 173!Uo!N  /  dx = 42km [hires GCM]  /  Regular TI'
	title_axis	=	['East longitude','North latitude']
	title_user	=	'Wind velocity (m/s) and wind vectors' ;'Surface temperature (K)'

;;;;;*************************************** COLOR TABLES
	flag_cb		=	'true'	
	format		=	'(F4.1)' ;'(I0)'
	colors		=	64
	pal		=	22		;; GOOD: 4, 18, 22, 16, 37, 33, 39

;;;;;*************************************** FILL LIMITS
	minfield_init	=	0.     
	maxfield_init	=	25.  
        ;minfield_init   =       155.
        ;maxfield_init   =       175.

;;;;;*************************************** LIMIT TRICKS
		lim_max = maxfield_init & w=where((what_I_plot ge lim_max) and (what_I_plot le 1e9)) & if (w[0] ne -1) then what_I_plot[w]=lim_max 
		lim_min = minfield_init & w=where(what_I_plot le lim_min) & if (w[0] ne -1) then what_I_plot[w]=lim_min 
;		lim_blank = 2. & w=where(abs(what_I_plot) le lim_blank) & if (w[0] ne -1) then what_I_plot[w]=missing_value 

;;;;;*************************************** WINDS
	windex		=	25.
	stride		=	1. ;2.

;;;;;*************************************** CONTOUR
	lev 		= 	50. + 50.*findgen(20)

;;;;;*************************************** AXIS
	isotropic	=	'true' 
	intervalx	=	2.
	intervaly	=	2.

;;;;;*************************************** MAP LIMITS
	windowx		=	[-144.,-126.] ;[-146.,-126.]
	windowy		=	[10.,26.] ;[10.,28.]




;;;;;*************************************** 
;;;;;*************************************** 
;;;;;*************************************** 
;;;;;*************************************** 




;;;
;;; VERTICAL SECTION LIMITS
;;;
;minalt=-5.		;; grepSEC
;maxalt=40.		;; grepSEC
;minspace=0.0  		;; grepSEC
;maxspace=35.0 		;; grepSEC

;;;
;;; METRIC UNITS FOR VERTICAL SECTION
;;;
;factor=10.	   ;; grepSEC
;space=space*60. & spacekm='true'   	;; grepSEC
;minspace=minspace*60./factor       	;; grepSEC
;maxspace=maxspace*60./factor       	;; grepSEC
;intervalx=round(intervalx*60./factor)   ;; grepSEC


;;;
;;; TRICKS
;;;

;; pour tracer juste les vecteurs sur un fond uni ou vide
;pal=0						;; 1/4 grepMAP
;what_I_plot(*,*)=what_I_plot(*,*)*0.+0.2	;; 2/4 grepMAP
;what_I_plot(0,0)=0.				;; 3/4 grepMAP
;flag_cb='false'					;; 4/4 grepMAP

;;; truc pour tracer juste les contours et une zone grisee de topo 
;pal=0                                           ;; 1/9 grepALL
;w=where(abs(what_I_plot) lt missing_value) 	;; 2/9 grepALL
;what_I_plot[w]=0.   				;; 3/9 grepALL
;w=where(abs(what_I_plot) gt missing_value) 	;; 4/9 grepALL
;what_I_plot[w]=0.75 				;; 5/9 grepALL
;w=where(what_I_plot eq 0.) 			;; 6/9 grepALL
;what_I_plot[w]=missing_value   			;; 7/9 grepALL
;what_I_plot(0,0)=1. & what_I_plot(1,0)=0.	;; 8/9 grepALL
;flag_cb='false'                         	;; 9/9 grepALL



